my_new_project:  # your profile name from dbt_project.yml
  target: dev    
  # your development environment
  outputs:
    
    dev:
      type: bigquery
      method: oauth
      project: my-gcp-learning-2022  
      # name of the project in BigQuery
      dataset: liveability  
      # your dataset for development (usually your name)
      threads: 4
      timeout_seconds: 300
      priority: interactive
      retries: 1
    
    prod: # your production environment
      type: bigquery
      method: oauth
      project: my-gcp-learning-2022  
      # name of the project in BigQuery
      dataset: liveability  
      # your dataset for production
      threads: 4
      timeout_seconds: 300
      priority: interactive
      retries: 1